export const businessCategories = [
  { value: null, label: "Select Category" },
  { value: "agriculture", label: "Agriculture" },
  { value: "automotive", label: "Automotive" },
  { value: "beauty", label: "Beauty & Personal Care" },
  { value: "construction", label: "Construction" },
  { value: "education", label: "Education" },
  { value: "finance", label: "Finance & Insurance" },
  { value: "food_beverage", label: "Food & Beverage" },
  { value: "health_medical", label: "Health & Medical" },
  { value: "home_services", label: "Home Services" },
  { value: "hospitality_tourism", label: "Hospitality & Tourism" },
  { value: "it_software", label: "IT & Software" },
  { value: "legal", label: "Legal Services" },
  { value: "manufacturing", label: "Manufacturing" },
  { value: "media_entertainment", label: "Media & Entertainment" },
  { value: "non_profit", label: "Non-Profit" },
  { value: "real_estate", label: "Real Estate" },
  { value: "retail", label: "Retail" },
  { value: "transportation_logistics", label: "Transportation & Logistics" },
  { value: "other", label: "Other" },
];
