export const COUNTRIES_DATA = [
  { label: "Afghanistan", flag: "🇦🇫", code: "AF", dialCode: "+93" },
  { label: "Åland Islands", flag: "🇦🇽", code: "AX", dialCode: "+358" },
  { label: "Albania", flag: "🇦🇱", code: "AL", dialCode: "+355" },
  { label: "Algeria", flag: "🇩🇿", code: "DZ", dialCode: "+213" },
  { label: "American Samoa", flag: "🇦🇸", code: "AS", dialCode: "+1684" },
  { label: "Andorra", flag: "🇦🇩", code: "AD", dialCode: "+376" },
  { label: "Angola", flag: "🇦🇴", code: "AO", dialCode: "+244" },
  { label: "Anguilla", flag: "🇦🇮", code: "AI", dialCode: "+1264" },
  { label: "Antarctica", flag: "🇦🇶", code: "AQ", dialCode: "+672" },
  { label: "Antigua and Barbuda", flag: "🇦🇬", code: "AG", dialCode: "+1268" },
  { label: "Argentina", flag: "🇦🇷", code: "AR", dialCode: "+54" },
  { label: "Armenia", flag: "🇦🇲", code: "AM", dialCode: "+374" },
  { label: "Aruba", flag: "🇦🇼", code: "AW", dialCode: "+297" },
  { label: "Australia", flag: "🇦🇺", code: "AU", dialCode: "+61" },
  { label: "Austria", flag: "🇦🇹", code: "AT", dialCode: "+43" },
  { label: "Azerbaijan", flag: "🇦🇿", code: "AZ", dialCode: "+994" },
  { label: "Bahamas", flag: "🇧🇸", code: "BS", dialCode: "+1242" },
  { label: "Bahrain", flag: "🇧🇭", code: "BH", dialCode: "+973" },
  { label: "Bangladesh", flag: "🇧🇩", code: "BD", dialCode: "+880" },
  { label: "Barbados", flag: "🇧🇧", code: "BB", dialCode: "+1246" },
  { label: "Belarus", flag: "🇧🇾", code: "BY", dialCode: "+375" },
  { label: "Belgium", flag: "🇧🇪", code: "BE", dialCode: "+32" },
  { label: "Belize", flag: "🇧🇿", code: "BZ", dialCode: "+501" },
  { label: "Benin", flag: "🇧🇯", code: "BJ", dialCode: "+229" },
  { label: "Bermuda", flag: "🇧🇲", code: "BM", dialCode: "+1441" },
  { label: "Bhutan", flag: "🇧🇹", code: "BT", dialCode: "+975" },
  {
    label: "Bolivia, Plurinational State of bolivia",
    flag: "🇧🇴",
    code: "BO",
    dialCode: "+591",
  },
  { label: "Bosnia and Herzegovina", flag: "🇧🇦", code: "BA", dialCode: "+387" },
  { label: "Botswana", flag: "🇧🇼", code: "BW", dialCode: "+267" },
  { label: "Bouvet Island", flag: "🇧🇻", code: "BV", dialCode: "+47" },
  { label: "Brazil", flag: "🇧🇷", code: "BR", dialCode: "+55" },
  {
    label: "British Indian Ocean Territory",
    flag: "🇮🇴",
    code: "IO",
    dialCode: "+246",
  },
  { label: "Brunei Darussalam", flag: "🇧🇳", code: "BN", dialCode: "+673" },
  { label: "Bulgaria", flag: "🇧🇬", code: "BG", dialCode: "+359" },
  { label: "Burkina Faso", flag: "🇧🇫", code: "BF", dialCode: "+226" },
  { label: "Burundi", flag: "🇧🇮", code: "BI", dialCode: "+257" },
  { label: "Cambodia", flag: "🇰🇭", code: "KH", dialCode: "+855" },
  { label: "Cameroon", flag: "🇨🇲", code: "CM", dialCode: "+237" },
  { label: "Canada", flag: "🇨🇦", code: "CA", dialCode: "+1" },
  { label: "Cape Verde", flag: "🇨🇻", code: "CV", dialCode: "+238" },
  { label: "Cayman Islands", flag: "🇰🇾", code: "KY", dialCode: "+345" },
  {
    label: "Central African Republic",
    flag: "🇨🇫",
    code: "CF",
    dialCode: "+236",
  },
  { label: "Chad", flag: "🇹🇩", code: "TD", dialCode: "+235" },
  { label: "Chile", flag: "🇨🇱", code: "CL", dialCode: "+56" },
  { label: "China", flag: "🇨🇳", code: "CN", dialCode: "+86" },
  { label: "Christmas Island", flag: "🇨🇽", code: "CX", dialCode: "+61" },
  { label: "Cocos (Keeling) Islands", flag: "🇨🇨", code: "CC", dialCode: "+61" },
  { label: "Colombia", flag: "🇨🇴", code: "CO", dialCode: "+57" },
  { label: "Comoros", flag: "🇰🇲", code: "KM", dialCode: "+269" },
  { label: "Congo", flag: "🇨🇬", code: "CG", dialCode: "+242" },
  {
    label: "Congo, The Democratic Republic of the Congo",
    flag: "🇨🇩",
    code: "CD",
    dialCode: "+243",
  },
  { label: "Cook Islands", flag: "🇨🇰", code: "CK", dialCode: "+682" },
  { label: "Costa Rica", flag: "🇨🇷", code: "CR", dialCode: "+506" },
  { label: "Cote d'Ivoire", flag: "🇨🇮", code: "CI", dialCode: "+225" },
  { label: "Croatia", flag: "🇭🇷", code: "HR", dialCode: "+385" },
  { label: "Cuba", flag: "🇨🇺", code: "CU", dialCode: "+53" },
  { label: "Cyprus", flag: "🇨🇾", code: "CY", dialCode: "+357" },
  { label: "Czech Republic", flag: "🇨🇿", code: "CZ", dialCode: "+420" },
  { label: "Denmark", flag: "🇩🇰", code: "DK", dialCode: "+45" },
  { label: "Djibouti", flag: "🇩🇯", code: "DJ", dialCode: "+253" },
  { label: "Dominica", flag: "🇩🇲", code: "DM", dialCode: "+1767" },
  { label: "Dominican Republic", flag: "🇩🇴", code: "DO", dialCode: "+1849" },
  { label: "Ecuador", flag: "🇪🇨", code: "EC", dialCode: "+593" },
  { label: "Egypt", flag: "🇪🇬", code: "EG", dialCode: "+20" },
  { label: "El Salvador", flag: "🇸🇻", code: "SV", dialCode: "+503" },
  { label: "Equatorial Guinea", flag: "🇬🇶", code: "GQ", dialCode: "+240" },
  { label: "Eritrea", flag: "🇪🇷", code: "ER", dialCode: "+291" },
  { label: "Estonia", flag: "🇪🇪", code: "EE", dialCode: "+372" },
  { label: "Ethiopia", flag: "🇪🇹", code: "ET", dialCode: "+251" },
  {
    label: "Falkland Islands (Malvinas)",
    flag: "🇫🇰",
    code: "FK",
    dialCode: "+500",
  },
  { label: "Faroe Islands", flag: "🇫🇴", code: "FO", dialCode: "+298" },
  { label: "Fiji", flag: "🇫🇯", code: "FJ", dialCode: "+679" },
  { label: "Finland", flag: "🇫🇮", code: "FI", dialCode: "+358" },
  { label: "France", flag: "🇫🇷", code: "FR", dialCode: "+33" },
  { label: "French Guiana", flag: "🇬🇫", code: "GF", dialCode: "+594" },
  { label: "French Polynesia", flag: "🇵🇫", code: "PF", dialCode: "+689" },
  {
    label: "French Southern Territories",
    flag: "🇹🇫",
    code: "TF",
    dialCode: "+262",
  },
  { label: "Gabon", flag: "🇬🇦", code: "GA", dialCode: "+241" },
  { label: "Gambia", flag: "🇬🇲", code: "GM", dialCode: "+220" },
  { label: "Georgia", flag: "🇬🇪", code: "GE", dialCode: "+995" },
  { label: "Germany", flag: "🇩🇪", code: "DE", dialCode: "+49" },
  { label: "Ghana", flag: "🇬🇭", code: "GH", dialCode: "+233" },
  { label: "Gibraltar", flag: "🇬🇮", code: "GI", dialCode: "+350" },
  { label: "Greece", flag: "🇬🇷", code: "GR", dialCode: "+30" },
  { label: "Greenland", flag: "🇬🇱", code: "GL", dialCode: "+299" },
  { label: "Grenada", flag: "🇬🇩", code: "GD", dialCode: "+1473" },
  { label: "Guadeloupe", flag: "🇬🇵", code: "GP", dialCode: "+590" },
  { label: "Guam", flag: "🇬🇺", code: "GU", dialCode: "+1671" },
  { label: "Guatemala", flag: "🇬🇹", code: "GT", dialCode: "+502" },
  { label: "Guernsey", flag: "🇬🇬", code: "GG", dialCode: "+44" },
  { label: "Guinea", flag: "🇬🇳", code: "GN", dialCode: "+224" },
  { label: "Guinea-Bissau", flag: "🇬🇼", code: "GW", dialCode: "+245" },
  { label: "Guyana", flag: "🇬🇾", code: "GY", dialCode: "+592" },
  { label: "Haiti", flag: "🇭🇹", code: "HT", dialCode: "+509" },
  {
    label: "Heard Island and Mcdonald Islands",
    flag: "🇭🇲",
    code: "HM",
    dialCode: "+672",
  },
  {
    label: "Holy See (Vatican City State)",
    flag: "🇻🇦",
    code: "VA",
    dialCode: "+379",
  },
  { label: "Honduras", flag: "🇭🇳", code: "HN", dialCode: "+504" },
  { label: "Hong Kong", flag: "🇭🇰", code: "HK", dialCode: "+852" },
  { label: "Hungary", flag: "🇭🇺", code: "HU", dialCode: "+36" },
  { label: "Iceland", flag: "🇮🇸", code: "IS", dialCode: "+354" },
  { label: "India", flag: "🇮🇳", code: "IN", dialCode: "+91" },
  { label: "Indonesia", flag: "🇮🇩", code: "ID", dialCode: "+62" },
  {
    label: "Iran, Islamic Republic of Persian Gulf",
    flag: "🇮🇷",
    code: "IR",
    dialCode: "+98",
  },
  { label: "Iraq", flag: "🇮🇶", code: "IQ", dialCode: "+964" },
  { label: "Ireland", flag: "🇮🇪", code: "IE", dialCode: "+353" },
  { label: "Isle of Man", flag: "🇮🇲", code: "IM", dialCode: "+44" },
  { label: "Israel", flag: "🇮🇱", code: "IL", dialCode: "+972" },
  { label: "Italy", flag: "🇮🇹", code: "IT", dialCode: "+39" },
  { label: "Jamaica", flag: "🇯🇲", code: "JM", dialCode: "+1876" },
  { label: "Japan", flag: "🇯🇵", code: "JP", dialCode: "+81" },
  { label: "Jersey", flag: "🇯🇪", code: "JE", dialCode: "+44" },
  { label: "Jordan", flag: "🇯🇴", code: "JO", dialCode: "+962" },
  { label: "Kazakhstan", flag: "🇰🇿", code: "KZ", dialCode: "+7" },
  { label: "Kenya", flag: "🇰🇪", code: "KE", dialCode: "+254" },
  { label: "Kiribati", flag: "🇰🇮", code: "KI", dialCode: "+686" },
  {
    label: "Korea, Democratic People's Republic of Korea",
    flag: "🇰🇵",
    code: "KP",
    dialCode: "+850",
  },
  {
    label: "Korea, Republic of South Korea",
    flag: "🇰🇷",
    code: "KR",
    dialCode: "+82",
  },
  { label: "Kosovo", flag: "🇽🇰", code: "XK", dialCode: "+383" },
  { label: "Kuwait", flag: "🇰🇼", code: "KW", dialCode: "+965" },
  { label: "Kyrgyzstan", flag: "🇰🇬", code: "KG", dialCode: "+996" },
  { label: "Laos", flag: "🇱🇦", code: "LA", dialCode: "+856" },
  { label: "Latvia", flag: "🇱🇻", code: "LV", dialCode: "+371" },
  { label: "Lebanon", flag: "🇱🇧", code: "LB", dialCode: "+961" },
  { label: "Lesotho", flag: "🇱🇸", code: "LS", dialCode: "+266" },
  { label: "Liberia", flag: "🇱🇷", code: "LR", dialCode: "+231" },
  { label: "Libyan Arab Jamahiriya", flag: "🇱🇾", code: "LY", dialCode: "+218" },
  { label: "Liechtenstein", flag: "🇱🇮", code: "LI", dialCode: "+423" },
  { label: "Lithuania", flag: "🇱🇹", code: "LT", dialCode: "+370" },
  { label: "Luxembourg", flag: "🇱🇺", code: "LU", dialCode: "+352" },
  { label: "Macao", flag: "🇲🇴", code: "MO", dialCode: "+853" },
  { label: "Macedonia", flag: "🇲🇰", code: "MK", dialCode: "+389" },
  { label: "Madagascar", flag: "🇲🇬", code: "MG", dialCode: "+261" },
  { label: "Malawi", flag: "🇲🇼", code: "MW", dialCode: "+265" },
  { label: "Malaysia", flag: "🇲🇾", code: "MY", dialCode: "+60" },
  { label: "Maldives", flag: "🇲🇻", code: "MV", dialCode: "+960" },
  { label: "Mali", flag: "🇲🇱", code: "ML", dialCode: "+223" },
  { label: "Malta", flag: "🇲🇹", code: "MT", dialCode: "+356" },
  { label: "Marshall Islands", flag: "🇲🇭", code: "MH", dialCode: "+692" },
  { label: "Martinique", flag: "🇲🇶", code: "MQ", dialCode: "+596" },
  { label: "Mauritania", flag: "🇲🇷", code: "MR", dialCode: "+222" },
  { label: "Mauritius", flag: "🇲🇺", code: "MU", dialCode: "+230" },
  { label: "Mayotte", flag: "🇾🇹", code: "YT", dialCode: "+262" },
  { label: "Mexico", flag: "🇲🇽", code: "MX", dialCode: "+52" },
  {
    label: "Micronesia, Federated States of Micronesia",
    flag: "🇫🇲",
    code: "FM",
    dialCode: "+691",
  },
  { label: "Moldova", flag: "🇲🇩", code: "MD", dialCode: "+373" },
  { label: "Monaco", flag: "🇲🇨", code: "MC", dialCode: "+377" },
  { label: "Mongolia", flag: "🇲🇳", code: "MN", dialCode: "+976" },
  { label: "Montenegro", flag: "🇲🇪", code: "ME", dialCode: "+382" },
  { label: "Montserrat", flag: "🇲🇸", code: "MS", dialCode: "+1664" },
  { label: "Morocco", flag: "🇲🇦", code: "MA", dialCode: "+212" },
  { label: "Mozambique", flag: "🇲🇿", code: "MZ", dialCode: "+258" },
  { label: "Myanmar", flag: "🇲🇲", code: "MM", dialCode: "+95" },
  { label: "Namibia", flag: "🇳🇦", code: "NA", dialCode: "+264" },
  { label: "Nauru", flag: "🇳🇷", code: "NR", dialCode: "+674" },
  { label: "Nepal", flag: "🇳🇵", code: "NP", dialCode: "+977" },
  { label: "Netherlands", flag: "🇳🇱", code: "NL", dialCode: "+31" },
  { label: "Netherlands Antilles", flag: "", code: "AN", dialCode: "+599" },
  { label: "New Caledonia", flag: "🇳🇨", code: "NC", dialCode: "+687" },
  { label: "New Zealand", flag: "🇳🇿", code: "NZ", dialCode: "+64" },
  { label: "Nicaragua", flag: "🇳🇮", code: "NI", dialCode: "+505" },
  { label: "Niger", flag: "🇳🇪", code: "NE", dialCode: "+227" },
  { label: "Nigeria", flag: "🇳🇬", code: "NG", dialCode: "+234" },
  { label: "Niue", flag: "🇳🇺", code: "NU", dialCode: "+683" },
  { label: "Norfolk Island", flag: "🇳🇫", code: "NF", dialCode: "+672" },
  {
    label: "Northern Mariana Islands",
    flag: "🇲🇵",
    code: "MP",
    dialCode: "+1670",
  },
  { label: "Norway", flag: "🇳🇴", code: "NO", dialCode: "+47" },
  { label: "Oman", flag: "🇴🇲", code: "OM", dialCode: "+968" },
  { label: "Pakistan", flag: "🇵🇰", code: "PK", dialCode: "+92" },
  { label: "Palau", flag: "🇵🇼", code: "PW", dialCode: "+680" },
  {
    label: "Palestinian Territory, Occupied",
    flag: "🇵🇸",
    code: "PS",
    dialCode: "+970",
  },
  { label: "Panama", flag: "🇵🇦", code: "PA", dialCode: "+507" },
  { label: "Papua New Guinea", flag: "🇵🇬", code: "PG", dialCode: "+675" },
  { label: "Paraguay", flag: "🇵🇾", code: "PY", dialCode: "+595" },
  { label: "Peru", flag: "🇵🇪", code: "PE", dialCode: "+51" },
  { label: "Philippines", flag: "🇵🇭", code: "PH", dialCode: "+63" },
  { label: "Pitcairn", flag: "🇵🇳", code: "PN", dialCode: "+64" },
  { label: "Poland", flag: "🇵🇱", code: "PL", dialCode: "+48" },
  { label: "Portugal", flag: "🇵🇹", code: "PT", dialCode: "+351" },
  { label: "Puerto Rico", flag: "🇵🇷", code: "PR", dialCode: "+1939" },
  { label: "Qatar", flag: "🇶🇦", code: "QA", dialCode: "+974" },
  { label: "Romania", flag: "🇷🇴", code: "RO", dialCode: "+40" },
  { label: "Russia", flag: "🇷🇺", code: "RU", dialCode: "+7" },
  { label: "Rwanda", flag: "🇷🇼", code: "RW", dialCode: "+250" },
  { label: "Reunion", flag: "🇷🇪", code: "RE", dialCode: "+262" },
  { label: "Saint Barthelemy", flag: "🇧🇱", code: "BL", dialCode: "+590" },
  {
    label: "Saint Helena, Ascension and Tristan Da Cunha",
    flag: "🇸🇭",
    code: "SH",
    dialCode: "+290",
  },
  { label: "Saint Kitts and Nevis", flag: "🇰🇳", code: "KN", dialCode: "+1869" },
  { label: "Saint Lucia", flag: "🇱🇨", code: "LC", dialCode: "+1758" },
  { label: "Saint Martin", flag: "🇲🇫", code: "MF", dialCode: "+590" },
  {
    label: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    code: "PM",
    dialCode: "+508",
  },
  {
    label: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    code: "VC",
    dialCode: "+1784",
  },
  { label: "Samoa", flag: "🇼🇸", code: "WS", dialCode: "+685" },
  { label: "San Marino", flag: "🇸🇲", code: "SM", dialCode: "+378" },
  { label: "Sao Tome and Principe", flag: "🇸🇹", code: "ST", dialCode: "+239" },
  { label: "Saudi Arabia", flag: "🇸🇦", code: "SA", dialCode: "+966" },
  { label: "Senegal", flag: "🇸🇳", code: "SN", dialCode: "+221" },
  { label: "Serbia", flag: "🇷🇸", code: "RS", dialCode: "+381" },
  { label: "Seychelles", flag: "🇸🇨", code: "SC", dialCode: "+248" },
  { label: "Sierra Leone", flag: "🇸🇱", code: "SL", dialCode: "+232" },
  { label: "Singapore", flag: "🇸🇬", code: "SG", dialCode: "+65" },
  { label: "Slovakia", flag: "🇸🇰", code: "SK", dialCode: "+421" },
  { label: "Slovenia", flag: "🇸🇮", code: "SI", dialCode: "+386" },
  { label: "Solomon Islands", flag: "🇸🇧", code: "SB", dialCode: "+677" },
  { label: "Somalia", flag: "🇸🇴", code: "SO", dialCode: "+252" },
  { label: "South Africa", flag: "🇿🇦", code: "ZA", dialCode: "+27" },
  { label: "South Sudan", flag: "🇸🇸", code: "SS", dialCode: "+211" },
  {
    label: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    code: "GS",
    dialCode: "+500",
  },
  { label: "Spain", flag: "🇪🇸", code: "ES", dialCode: "+34" },
  { label: "Sri Lanka", flag: "🇱🇰", code: "LK", dialCode: "+94" },
  { label: "Sudan", flag: "🇸🇩", code: "SD", dialCode: "+249" },
  { label: "Surilabel", flag: "🇸🇷", code: "SR", dialCode: "+597" },
  { label: "Svalbard and Jan Mayen", flag: "🇸🇯", code: "SJ", dialCode: "+47" },
  { label: "Eswatini", flag: "🇸🇿", code: "SZ", dialCode: "+268" },
  { label: "Sweden", flag: "🇸🇪", code: "SE", dialCode: "+46" },
  { label: "Switzerland", flag: "🇨🇭", code: "CH", dialCode: "+41" },
  { label: "Syrian Arab Republic", flag: "🇸🇾", code: "SY", dialCode: "+963" },
  { label: "Taiwan", flag: "🇹🇼", code: "TW", dialCode: "+886" },
  { label: "Tajikistan", flag: "🇹🇯", code: "TJ", dialCode: "+992" },
  {
    label: "Tanzania, United Republic of Tanzania",
    flag: "🇹🇿",
    code: "TZ",
    dialCode: "+255",
  },
  { label: "Thailand", flag: "🇹🇭", code: "TH", dialCode: "+66" },
  { label: "Timor-Leste", flag: "🇹🇱", code: "TL", dialCode: "+670" },
  { label: "Togo", flag: "🇹🇬", code: "TG", dialCode: "+228" },
  { label: "Tokelau", flag: "🇹🇰", code: "TK", dialCode: "+690" },
  { label: "Tonga", flag: "🇹🇴", code: "TO", dialCode: "+676" },
  { label: "Trinidad and Tobago", flag: "🇹🇹", code: "TT", dialCode: "+1868" },
  { label: "Tunisia", flag: "🇹🇳", code: "TN", dialCode: "+216" },
  { label: "Turkey", flag: "🇹🇷", code: "TR", dialCode: "+90" },
  { label: "Turkmenistan", flag: "🇹🇲", code: "TM", dialCode: "+993" },
  {
    label: "Turks and Caicos Islands",
    flag: "🇹🇨",
    code: "TC",
    dialCode: "+1649",
  },
  { label: "Tuvalu", flag: "🇹🇻", code: "TV", dialCode: "+688" },
  { label: "Uganda", flag: "🇺🇬", code: "UG", dialCode: "+256" },
  { label: "Ukraine", flag: "🇺🇦", code: "UA", dialCode: "+380" },
  { label: "United Arab Emirates", flag: "🇦🇪", code: "AE", dialCode: "+971" },
  { label: "United Kingdom", flag: "🇬🇧", code: "GB", dialCode: "+44" },
  { label: "United States", flag: "🇺🇸", code: "US", dialCode: "+1" },
  { label: "Uruguay", flag: "🇺🇾", code: "UY", dialCode: "+598" },
  { label: "Uzbekistan", flag: "🇺🇿", code: "UZ", dialCode: "+998" },
  { label: "Vanuatu", flag: "🇻🇺", code: "VU", dialCode: "+678" },
  {
    label: "Venezuela, Bolivarian Republic of Venezuela",
    flag: "🇻🇪",
    code: "VE",
    dialCode: "+58",
  },
  { label: "Vietnam", flag: "🇻🇳", code: "VN", dialCode: "+84" },
  {
    label: "Virgin Islands, British",
    flag: "🇻🇬",
    code: "VG",
    dialCode: "+1284",
  },
  { label: "Virgin Islands, U.S.", flag: "🇻🇮", code: "VI", dialCode: "+1340" },
  { label: "Wallis and Futuna", flag: "🇼🇫", code: "WF", dialCode: "+681" },
  { label: "Yemen", flag: "🇾🇪", code: "YE", dialCode: "+967" },
  { label: "Zambia", flag: "🇿🇲", code: "ZM", dialCode: "+260" },
  { label: "Zimbabwe", flag: "🇿🇼", code: "ZW", dialCode: "+263" },
];
